
---

## 🛠️ `azure-pipelines.yml` – For Azure DevOps

Here's a simple and clean Cypress pipeline YAML file:

```yaml
trigger:
  - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run cypress:run
    displayName: 'Run Cypress Tests (DEV & QA)'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/cypress/results/*.xml'
      failTaskOnFailedTests: true
    displayName: 'Publish test results'
